# ============================================================================
#  proxy.conf — Satellite (generado por deploy.sh)
#  NO editar manualmente — cambiar valores en .env y re-ejecutar deploy.sh
# ============================================================================

proxy server {
    default_fallback = no
}

# Mothership — Servidor Master en AWS
home_server upeu-aws-mothership {
    type = auth+acct
    ipaddr = %%MOTHERSHIP_IP%%
    port = 1812
    secret = '%%SECRET_SATELLITE_MOTHERSHIP%%'
    require_message_authenticator = yes

    response_window = %%PROXY_RESPONSE_WINDOW%%
    zombie_period = %%PROXY_ZOMBIE_PERIOD%%
    revive_interval = %%PROXY_REVIVE_INTERVAL%%

    status_check = status-server
    check_interval = 30
    check_timeout = 3
    num_answers_to_alive = 3
    max_outstanding = 65536

    coa {
        irt = 2
        mrt = 16
        mrc = 5
        mrd = 30
    }

    limit {
        max_connections = 16
        max_requests = 0
        lifetime = 0
        idle_timeout = 0
    }
}

# Pool de servidores (fail-over)
home_server_pool upeu-pool-cloud-auth {
    type = fail-over
    home_server = upeu-aws-mothership
}

# Realms — todas las peticiones van a la Mothership
realm upeu.edu.pe {
    auth_pool = upeu-pool-cloud-auth
    acct_pool = upeu-pool-cloud-auth
}

realm LOCAL {
    auth_pool = upeu-pool-cloud-auth
    acct_pool = upeu-pool-cloud-auth
}

realm NULL {
    auth_pool = upeu-pool-cloud-auth
    acct_pool = upeu-pool-cloud-auth
}
