# ============================================================================
#  clients.conf — Mothership (generado por deploy.sh)
#  NO editar manualmente — cambiar valores en .env y re-ejecutar deploy.sh
# ============================================================================

client localhost {
    ipaddr = 127.0.0.1
    proto = *
    secret = testing123
    nas_type = other
    limit {
        max_connections = 16
        lifetime = 0
        idle_timeout = 30
    }
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = testing123
}

# Satellite: %%SAT_NAME%%
client %%SAT_SHORTNAME%% {
    ipaddr    = %%SAT_PUBLIC_IP%%
    secret    = %%SECRET_SATELLITE_MOTHERSHIP%%
    shortname = %%SAT_SHORTNAME%%
    require_message_authenticator = yes
    limit_proxy_state = yes
}
