eap {
    default_eap_type = %%EAP_DEFAULT_TYPE%%
    timer_expire = 60
    ignore_unknown_eap_types = no
    cisco_accounting_username_bug = no
    max_sessions = ${max_requests}

    tls-config tls-common {
        private_key_file = %%CERT_PRIVATE_KEY%%
        certificate_file = %%CERT_CERTIFICATE%%
        ca_file = %%CERT_CA_FILE%%
        ca_path = /etc/freeradius/3.0/certs
        dh_file = /etc/freeradius/3.0/certs/dh
        random_file = /dev/urandom
        fragment_size = 1024
        include_length = yes
        tls_min_version = "%%TLS_MIN_VERSION%%"
        tls_max_version = "%%TLS_MAX_VERSION%%"
        cipher_list = "%%TLS_CIPHER_LIST%%"
        ecdh_curve = "%%TLS_ECDH_CURVE%%"
        cache {
            enable = yes
            lifetime = %%TLS_CACHE_LIFETIME%%
            name = "EAP_TLS_Cache"
            max_entries = %%TLS_CACHE_MAX_ENTRIES%%
            persist_dir = "/var/log/freeradius/tlscache"
        }
    }

    tls {
        tls = tls-common
    }

    md5 {
    }

    mschapv2 {
    }

    peap {
        tls = tls-common
        default_eap_type = mschapv2
        virtual_server = inner-tunnel
    }

    ttls {
        tls = tls-common
        default_eap_type = md5
        virtual_server = inner-tunnel
    }
}
